Makefile
Teaching-projects/SZE-MOSZE-2020-Memory-leak pull request #12
Opened 2020-10-28 14:49 UTC by Krisiiii98

Workflow-k átalakítása make segítségével.

2020-10-29 09:33 UTC, hegyhati requested changes
A header dependency fontos, a tobbi stilisztikai eszrevetel.

2020-10-29 09:33 UTC, hegyhati commented on .github/workflows/testing_outputs.yml
> +                - run: make memoryleak
hat... nem akarunk memory leaket csinalni, inkabb memchek-et vagy memleak check-et :-) de amugy ok.

2020-10-29 09:33 UTC, hegyhati commented on .github/workflows/testing_outputs.yml
> +                - run: make fight && cd test && diff result.txt expected.txt
ezt en akkor definialnam egy uj targetnek, hogy fightdiff, ami dependel a fight-ra, es utana cd ..

2020-10-29 09:33 UTC, hegyhati commented on Makefile
> +	g++ -Wall -c jsonParser.cpp
Hianyolom a headoroket.

2020-10-29 09:33 UTC, hegyhati commented on Makefile
> +	./run-test test/units/kekarott.json test/units/kikarott.json >> test/result.txt
Neztem egy ideig, mire leesett -.-  de akkor mar irhattal volna ciklust is.

2020-10-29 20:05 UTC, Krisiiii98 commented
Elkészültek a javítások. @hegyhati

2020-10-31 19:19 UTC, hegyhati commented on Makefile
> +Hero.o: Hero.cpp Hero.h
A Hero-nak elmeletileg kellene hasznalnia a jsonparsert, nem?

2020-11-01 19:41 UTC, Krisiiii98 commented
Kész a javítás.

2020-11-02 00:37 UTC, hegyhati commented on Makefile
>  main.o: main.cpp
es a main-ben nem hasznalod a hero-t meg a tobbit? Ha jelzek egy hibat tessek megnezni, hogy ugyanaz a hiba mashol nem fordul-e elo.

2020-11-02 19:02 UTC, Krisiiii98 commented
Kész, több head-t már nem látok :)

2020-11-03 10:00 UTC, hegyhati approved these changes

2020-11-03 10:00 UTC, merged