Refactor
Teaching-projects/SZE-MOSZE-2020-Memory-leak pull request #13
Opened 2020-11-02 19:25 UTC by joostibor

Make code refactoring and update needed files.

2020-11-03 11:59 UTC, joostibor commented
@hegyhati Sajnos a git mv nálunk is "bebuggolt" egy esetben, ez a `b3318c5` commitban van. git mv-vel átneveztem a parserTest.yml-t de valamiért nem vette az adást. De ahogy írtad a közös oldalon UPDATE-ban, látni láthatóak szerintem mik módosultak. Illetve a változtatások megyeznek az [itt találhatóakkal](https://github.com/Teaching-projects/SZE-MOSZE-2020-Memory-leak/commit/376187ab4ebecf33b4b1b9af9e96e17fb0badd92#diff-abd737a66acf01ececc1c7c582e11afd68e0fbaf20ba2ba29a5187240b71f500).

2020-11-04 16:23 UTC, hegyhati requested changes
Rendben van, de a ket teszt ket kulon fajlba menjen, es ket diff legyen. Ha lesz 50 teszted, maceras lesz igy kitalalni, melyik scenariora hasalt el. Ezt meg csinaljatok meg, aztan mehet be. (Ha szepen akarjatok megcsinalni, akkor ajanlok guglizni a "build matrix" es esetleg a "dynamic github actions pipeline" fogalmakra. A SOE-Progalap-2020-HF repomban lathattok ilyesmit.

2020-11-04 18:08 UTC, joostibor commented
@hegyhati tesztestek szétszedve. Megnéztük a mintákat guglin is, meg a repoban is, de úgy dönöttünk két teszt most a határidő, hazautazás stb. miatt legyen így "rondán", természtesen ha a későbbiekben több teszt kell nem másolunk sort, mert nyilván szebb a matrix és nem lehetetlen.

2020-11-04 18:25 UTC, hegyhati approved these changes
a matrix csak opcio volt, teljesen jo igy

2020-11-04 18:26 UTC, merged