Game pimp
Teaching-projects/SZE-MOSZE-2020-Memory-leak pull request #16
Opened 2020-11-23 20:15 UTC by Peti96

Add new features to the project

2020-11-26 20:08 UTC, AnonymDavid commented on Game.cpp
> +    if (isOccupied(x,y) || gameMap.get(x,y) == Map::type::Wall) throw OccupiedException("This position is occupied!");
Hero kerülhet olyan mezőre, ahol már van monster

2020-11-26 20:13 UTC, AnonymDavid requested changes
Egy dolog, ami nemrég merült fel kérdésként a feladattal kapcsolatban, azon kívül jó a kód 👍

2020-11-26 21:11 UTC, joostibor commented
Javítja.

2020-11-28 09:54 UTC, AnonymDavid approved these changes
Jól néz ki 👍

2020-11-28 10:19 UTC, nemethvalentin approved these changes

2020-11-28 10:24 UTC, joostibor approved these changes

2020-11-28 10:24 UTC, merged