Levelup
Teaching-projects/SZE-MOSZE-2020-Memory-leak pull request #7
Opened 2020-10-15 14:18 UTC by Krisiiii98

Kód elkészítése a 3-as feladat level-up részéhez és git action kiegészítése memoria szemét vizsgálattal és statikus kódanalízissel.

2020-10-17 14:17 UTC, oliverosz requested changes
Ha ezt a két apróságot javítottátok, utána frissítsétek a branchet a masterre, és oldjátok fel a konfliktusokat.

2020-10-17 14:17 UTC, oliverosz commented on Hero.cpp
> +	h.xp += h.getDmg();
Ha az áldozatnak ennél kevesebb élete van, akkor csak annyi xp-t kapjon a hős, amennyi életet le tudott vonni.

2020-10-17 14:17 UTC, oliverosz commented on Hero.cpp
> +		h.maxhp *= 1.10;
hiányzik a kerekítés

2020-10-19 18:00 UTC, joostibor commented
@oliverosz elkészültünk a javításokkal, illetve a conflictok feloldásával. Az xp hozzárendelős logikánkon észrevettük a hibát és mivel a javítás kódismétlés lett volna ezért készítettünk egy új függvényt, reméljük nem baj ez és most már helyes a működés.
A doxygent kiegészítettük az új függvényekre is.

2020-10-21 15:11 UTC, oliverosz commented
Valami nem jó. Duplikálódtak a commitok. Ha tippelnem kéne, valaki rebase-elt a mastrre, majd az így kapott branchbe merge-elte a rebase előtti állapotot.

A 6d22984 commit még jó, ez a rebase-elt állapot, innen kéne folytatni a hibák javítását és force push-sal feltölteni a javított verziót.

2020-10-21 19:52 UTC, joostibor commented
@oliverosz Elkészültünk a javítással. Sajnos valóban igazad volt, valamit félrecsúszott ezelőtt, igyekeztünk javítani a dolgot. + Hiányzott az attack speed csökkentése szintlépéskor, ezt pótoltuk.

2020-10-21 20:49 UTC, oliverosz approved these changes
Rendben, így jónak tűnik.

2020-10-21 20:50 UTC, merged