Jsonparser
Teaching-projects/SZE-MOSZE-2020-Memory-leak pull request #8
Opened 2020-10-15 20:34 UTC by joostibor

Jsonparser külön osztályba helyezése a #3-as feladatnak megfelelően. A parser bővítésre került háromféle bemenetre, ezekhez pedig készült 1-1 unit test googleteszt segítségével. 

Emellett a #2-es feladat elfogadásánál kérés volt a parser nagymértékű fejlesztése, azonban úgy dönöttem csak a nagyon alapokat meghagyva új alapokra helyezem a parsolást. Függvény készült az értékek "maszlagmentesítésére", típus definiálást végeztem a könnyebb átláthatóság érdekében és változás történt a logikában is.

A tesztek futtásához új workflow-t készítettem a GHA-ban.

2020-10-19 15:43 UTC, joostibor commented
@wajzy nem maradtunk ki az átnézésből?

2020-10-20 14:32 UTC, wajzy requested changes
Picit még finomítsd a kódot a megjegyzéseknek megfelelően!

2020-10-20 14:32 UTC, wajzy commented on jsonParser.cpp
> +        return line.substr(firstQoMarkpos + 1, lastQoMarkpos - (firstQoMarkpos + 1));
Ezzel még mindig lehet gond, ha csak egyetlen " van a szövegben.

2020-10-20 14:32 UTC, wajzy commented on jsonParser.cpp
> +        if (input.find('{') < 0) { throw HeroFileError("Can't open the json file."); }
Nem egészen világos nekem, mit keres ez itt. Semmiképpen se végezze ugyanaz a függvény kétféle lehetséges módon adott bemenet feldolgozását (fájlnév, stringben adott JSON tartalom)!

2020-10-20 14:32 UTC, wajzy commented on jsonParser.h
> +    static jsonMap parse(std::istream& inputStream);
Ide kerüljön be még egy fv. a 3. lehetséges esetnek. Igen, annak is string lesz a paramétere, tudom, és nem tilos átnevezni a függvényeket.

2020-10-20 14:32 UTC, wajzy commented on test/jsonparserTest.cpp
> +}
Eddig jó, de szeretném látni, hogy a parzer elboldogul legalább néhány, könnyen előforduló hibával is json fájlban. Készüljön ennek ellenőrzésére is teszteset!

2020-10-21 12:08 UTC, joostibor commented
@wajzy elkészültek a kért módosítások.

2020-10-24 08:56 UTC, joostibor commented
@wajzy

2020-10-24 15:24 UTC, wajzy requested changes
Történt valami, de a badunit tesztelését még mindig nem látom, pedig nagyon érdekelne.

2020-10-24 15:24 UTC, wajzy commented on main.cpp
> +	(void)argc;
Ezt nem értem, miért van rá szükség?

2020-10-24 15:24 UTC, wajzy commented on test/jsonparserTest.cpp
> +}
Hát ez nem a JSON parzert teszteli, hanem saját magát.

2020-10-24 19:03 UTC, joostibor commented
@wajzy elkészültem a javításokkal. Hozzáadtam a badunit tesztelését is, ami pedig nem szervesen a parzolás teszteléséhez tartozik kiszerveztem külön tesztegységbe.

2020-10-24 19:04 UTC, joostibor commented on main.cpp
> +	(void)argc;
A warning elkerülése miatt volt rá szükség, de javítottam egy másik, (szebb?) megoldásra.

2020-10-25 08:17 UTC, wajzy approved these changes
OK

2020-10-25 08:18 UTC, wajzy commented
@joostibor Kezdheted feloldani az ütközéseket.

2020-10-25 17:35 UTC, joostibor commented
@wajzy elkészültek a conflictok feloldásai.

2020-10-27 11:42 UTC, wajzy approved these changes
OK

2020-10-27 11:43 UTC, merged